### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by jleclanche** [rafaelmartins/blohg#5]
Is this possible?

**Comment by RMCampos** [comment]
I'm trying to run with python3 (installing blohg with pip from git repo) and libapache2-mod-wsgi-py3. But it's not working.

Traceback: https://dpaste.com/FYSLVS3EY

It's related to python3 maybe?

Obs: running on Debian 9 (stable)

**Comment by rafaelmartins** [comment]
the error is in mercurial, but python 3.5 is too old anyway, you need at least 3.6.

closing as python 3 support was already implemented
